import { useState } from 'react'
import { supabase } from '../lib/supabaseClient'
import { B, bodyFont } from '../lib/theme'

// Team Access tab: list + add team members for this event, plus each
// member's check-in link. Team members are scoped per-event (not
// per-org) — matches the original schema, where `team_members.event_id`
// is the foreign key. `token` is auto-generated by the database on
// insert (see team_members.token default in the schema) — we don't set
// it client-side, just read it back to build the shareable link.
export default function TeamTab({ event, teamMembers, onTeamMembersChange }) {
  const [name, setName] = useState('')
  const [role, setRole] = useState('')
  const [errorMessage, setErrorMessage] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [copiedId, setCopiedId] = useState(null)

  const checkInUrl = (token) => `${window.location.origin}/checkin/${token}`

  const handleCopyLink = async (member) => {
    try {
      await navigator.clipboard.writeText(checkInUrl(member.token))
      setCopiedId(member.id)
      setTimeout(() => setCopiedId((current) => (current === member.id ? null : current)), 2000)
    } catch {
      // Clipboard API can fail (permissions, non-HTTPS context). Fall back
      // to just showing the link so it can be copied by hand instead of
      // failing silently.
      window.prompt('Copy this check-in link:', checkInUrl(member.token))
    }
  }

  const handleAdd = async (e) => {
    e.preventDefault()
    if (!name.trim()) return
    setSubmitting(true)
    setErrorMessage('')

    const { data, error } = await supabase
      .from('team_members')
      .insert({ event_id: event.id, name: name.trim(), role: role.trim() || null })
      .select()
      .single()

    setSubmitting(false)

    if (error) {
      setErrorMessage(`Could not add team member: ${error.message}`)
      return
    }

    onTeamMembersChange([...teamMembers, data])
    setName('')
    setRole('')
  }

  return (
    <div style={{ fontFamily: bodyFont }}>
      {teamMembers.length === 0 && <p style={styles.note}>No team members added yet.</p>}
      {teamMembers.map((member) => (
        <div key={member.id} style={styles.row}>
          <div>
            <span style={styles.name}>{member.name}</span>
            {member.role && <span style={styles.role}>{member.role}</span>}
          </div>
          <div style={styles.rowActions}>
            {member.checked_in ? (
              <span style={styles.checkedInBadge}>
                Checked in {member.checked_in_at ? new Date(member.checked_in_at).toLocaleTimeString() : ''}
              </span>
            ) : (
              <button
                type="button"
                style={styles.linkButton}
                onClick={() => handleCopyLink(member)}
                disabled={!member.token}
              >
                {copiedId === member.id ? 'Copied' : 'Copy check-in link'}
              </button>
            )}
          </div>
        </div>
      ))}

      <form onSubmit={handleAdd} style={styles.form}>
        <input
          style={styles.input}
          placeholder="Name"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <input
          style={styles.input}
          placeholder="Role (optional)"
          value={role}
          onChange={(e) => setRole(e.target.value)}
        />
        <button type="submit" style={styles.button} disabled={submitting}>
          {submitting ? 'Adding…' : 'Add'}
        </button>
      </form>
      {errorMessage && <p style={styles.error}>{errorMessage}</p>}
    </div>
  )
}

const styles = {
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 14px',
    border: `1px solid ${B.border}`,
    borderRadius: 4,
    marginBottom: 6,
    gap: 12,
  },
  rowActions: { flexShrink: 0 },
  name: { fontWeight: 600, fontSize: 14, marginRight: 8 },
  role: { color: B.inkLight, fontSize: 13 },
  linkButton: {
    padding: '6px 12px',
    background: 'transparent',
    border: `1px solid ${B.border}`,
    borderRadius: 4,
    fontSize: 12,
    color: B.inkMid,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  checkedInBadge: {
    fontSize: 12,
    color: '#2D6A4F',
    whiteSpace: 'nowrap',
  },
  note: { color: B.inkLight, fontSize: 14, marginBottom: 16 },
  form: { display: 'flex', gap: 8, marginTop: 16 },
  input: {
    flex: 1,
    padding: '10px 12px',
    border: `1px solid ${B.border}`,
    borderRadius: 4,
    fontSize: 14,
    fontFamily: bodyFont,
  },
  button: {
    padding: '10px 16px',
    background: B.ink,
    color: B.bg,
    border: 'none',
    borderRadius: 4,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  error: { color: B.red, fontSize: 13, marginTop: 8 },
}
